spring:
  datasource:
    url: jdbc:/mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8
    username:root
    password:geliyang
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-location: classpath:/mapping/*.xml
  type-aliases-package: com.example.demo.entity