spring:
  datasource:
    url: jdbc:/mysql://localhost:3307/mybatis?useUnicode=true&characterEncoding=UTF-8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.southwind.entity